web.php tasksのグループ化を実装しました。
tomoki23/laravel-todo pull request #1
Opened 2023-05-22 13:31 UTC by tomoki23

### web.php
・prefixを使用してグループ化しました。
・nameを最初に指定してコードを簡略化しました。

この変更によりルートの修正がしやすくなりました。

2023-05-23 01:01 UTC, MizukiMatsutani commented on routes/web.php
>      Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
@tomoki23 
profileもやっておくといいと思います！

2023-05-23 01:03 UTC, MizukiMatsutani commented on routes/web.php
> +        Route::delete('/{id}/delete', [TaskDeleteController::class, 'destroy'])->name('delete');
ちなみに、入れ子にもできます！（別に修正は不要です）

```
    Route::prefix('tasks')->name('tasks.')->group(function () {
        Route::get('', [TaskIndexController::class, 'index'])->name('index');
        Route::get('/create', [TaskCreateController::class, 'create'])->name('create');
        Route::post('/', [TaskStoreController::class, 'store'])->name('store');
        Route::prefix('/{id}')->group(function () {
            Route::get('/', [TaskShowController::class, 'show'])->name('show');
            Route::get('/edit', [TaskEditController::class, 'edit'])->name('edit');
            Route::put('/update', [TaskUpdateController::class, 'update'])->name('update');
            Route::delete('/delete', [TaskDeleteController::class, 'destroy'])->name('delete');
        });
    });
```

2023-05-23 01:03 UTC, MizukiMatsutani requested changes
確認ください！

2023-05-23 14:22 UTC, tomoki23 commented
### prefixを使用して{id}のグループ化を実装しました。

2023-05-25 08:21 UTC, MizukiMatsutani commented on routes/web.php
>      Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
@tomoki23 
こちらは対応しないですか？

2023-05-26 15:05 UTC, merged